version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Expose React frontend on port 3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../csvtojson
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose Spring Boot backend on port 8080
    networks:
      - app-network

networks:
  app-network:
